# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kauth': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kdeclarative': '@latest'
    'frameworks/kglobalaccel': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kidletime': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/kpackage': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/kwayland': '@latest'
    'frameworks/kwaylandserver': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'plasma/layer-shell-qt': '@same'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
